# close AutoTask Tickets by import of csv
# 9/5/2017 
# used this script to close 152 tickets 9/12/17 
# used this script to close 22 evt duplicate tickets 9/14/17 
# used this script to close 73 AT unassigned tickets with no matching open Ni2 ticket 9/21/17 - updated note section

# New-ATWSQuery include
. .\AT-New-ATWSQuery.ps1
# end external reference


# Username and password for Autotask 
 
# The username must begin with a backslash, otherwise Windows will add a domain
# element that Autotask do not understand.
# ======================================================================== 
# ~~~~!!!! for script to work - need to update username and password below
# ~~~~!!!! username should be inform of    \user@mail.com  ""
# best practice would be to either set up a service account to investigate whether AT supports an API key 
 
$username = "insert username here"
$password = ConvertTo-SecureString "insert password here" -AsPlainText -Force
$credentials = New-Object System.Management.Automation.PSCredential($username, $password) 

# Web services URL for Autotask (updated to point at region 5 for LE)
$atws = New-WebServiceProxy -URI https://webservices5.Autotask.net/atservices/1.5/atws.wsdl -Credential $credentials

# open file 
$ticketsToClose = Import-Csv .\CloseNoMatchNi2.csv | Select-Object "Ticket Number"
Write-Host "Beginning to process " $ticketsToClose.Count
Write-Host "========================================="
$ProcessedCount = 0 
foreach ($ticketNumber in $ticketsToClose) {
    $ticketQuery = New-ATWSQuery "Ticket" "TicketNumber" "Equals" $ticketNumber.'Ticket Number'
    $Result = $atws.query($ticketQuery)
    # should just be 1 tickedt - but loop through results 
    foreach ($ticket in $Result.EntityResults) {
        # sets ticket status to  5 complete -- status of XX  (cancelled=18)
            #$ticket.Status = 5
            #$atws.update($ticket)
            #Write-Host "Setting status to complete for ticket " $ticket.'TicketNumber'
            # create a note
            $noteToCreate = New-Object  Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy1k_net_atservices_1_5_atws_wsdl.TicketNote
            $noteToCreate.TicketID = $ticket.id
            $noteToCreate.Title = "Mx 09 21 2017 No Open Matching Ni2"
            $noteToCreate.Description = "Completing ticket. No open matching Ni2 ticket. The ticket in Ni2 was either completed or cancelled.  Completing this AT ticket as part of clean up."
            $noteToCreate.NoteType = 1
            $noteToCreate.Publish = 1
            $atws.create($notetoCreate)
            # creates a note on this ticket
            Write-Host "Added note to ticket " $ticketNumber.'TicketNumber'
            $ProcessedCount++
        }
        

}

Write-Host "========================================="
Write-Host "Completed Tickets " $ProcessedCount

#Write-host "Count of Tickets: " $($Result.EntityResults).Count
# Print any returned entities to console:
#$Result.EntityResults | Select-Object AccountID, Status, TicketNumber
# Import-Csv c:\scripts\test.txt | Sort-Object score | Select-Object -first 5
# from https://technet.microsoft.com/en-us/library/ee176900.aspx
